apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-api
spec:
  selector:
    matchLabels:
      app: spotify-api
  template:
    metadata:
      labels:
        app: spotify-api
    spec:
      containers:
      - name: spotify-api
        envFrom:
        - secretRef:
            name: spotify-api-access
        image: dixneuf19/spotify-api:4f11f18
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-api
spec:
  selector:
    app: spotify-api
  ports:
  - port: 1919
    targetPort: 80
---
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: spotify-api
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     ingress.kubernetes.io/ssl-redirect: "true"
# spec:
#   tls:
#   - hosts:
#     - spotify-api.dixneuf19.me
#     secretName: spotify-api-dixneuf19-me-tls
#   rules:
#   - host: spotify-api.dixneuf19.me 
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: spotify-api
#           servicePort: 80
